#server配置
server:
  port: 8096

#数据源配置
spring:
  datasource:
    driver-class-name: com.sap.db.jdbc.Driver
    username: SCI_APPLICATION
    password: Initial0
    url: jdbc:sap://10:122:13:22:30353?reconnect=true
  application:
    name: myEurekaDemo

#eureka配置
eureka:
  instance:
    hostname: localhost
    instance-id: myEurekaDemoService
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8096/eureka/




